services:
  postgres:
    image: postgres:16
    container_name: blog_postgres_db
    restart: always

    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: blog_admin
      POSTGRES_PASSWORD: blog_secret
      POSTGRES_DB: blogdb

    volumes:
      - blog_postgres_data:/var/lib/postgresql/data

volumes:
  blog_postgres_data:
